export const CREARTAREA = "CREARTAREA";
export const OBTENERTAREAS = "OBTENERTAREAS";
export const ACTUALIZARTAREA = "ACTUALIZARTAREA";
export const ELIMINARTAREA = "ELIMINARTAREA";
export const SHOWALERTA = 'SHOWALERTA';
export const HIDEALERTA = 'HIDEALERTA';
